### ISSUE TITLE
add a link to view website

### ISSUE THREAD

**Issue by plbstl** [Richmond-Eribo/Newsletter#1]
It would be nice for someone to easily navigate to the live version of the site from this repo

- [x] link in repo description 
- [x] link in readme file

**Comment by Richmond-Eribo** [comment]
Okay, will work on it.
What do you mean live version?

**Comment by plbstl** [comment]
I meant, put a link to view the website. http://mail.cnat.com.ng/

**Comment by Richmond-Eribo** [comment]
Closed All
